# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('team_type', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='cop_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cops', to='challenge.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='robber_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robbers', to='challenge.Team'),
        ),
    ]
