# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='hook',
        ),
        migrations.AddField(
            model_name='game',
            name='has_ended',
            field=models.BooleanField(default=False),
        ),
    ]
