# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20170910_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_cops', models.IntegerField()),
                ('num_robbers', models.IntegerField()),
                ('num_banks', models.IntegerField()),
            ],
        ),
    ]
