# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cols',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='labyrinth_degree',
            field=models.DecimalField(decimal_places=5, default=0.3, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='rows',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
