# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20170916_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cop_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='robber_score',
            field=models.IntegerField(default=0),
        ),
    ]
